name: Push Main

on:
  push:
    branches: [main]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      RSYNC_ADDRESS: ${{ secrets.RSYNC_ADDRESS }}
      RSYNC_PASSWORD: ${{ secrets.RSYNC_PASSWORD}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install node.js (lastest version)
        uses: actions/setup-node@v2

      - name: Deploy to hostinger
        run: npm run deploy:hostinger
