name: Push Main

on:
  push:
    branches: [main]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install node.js (lastest version)
        uses: actions/setup-node@v2

      - name: Install packages
        run: npm ci

      - name: Build export
        run: npm run export

      - name: rsync deployments
        uses: burnett01/rsync-deployments@3.0
        with:
          switches: -avzr --delete
          path: ./out
          remote_port: ${{ secrets.PORT }}
          remote_path: ${{ secrets.PATH }}
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
